Fix roots
semantic-math/math-rules pull request #49
Opened 2017-06-12 19:18 UTC by aliang8

Fixed the matchFn for nthRoot rules. Fixed build notation.

2017-06-13 01:58 UTC, k4b7 requested changes

2017-06-13 01:58 UTC, kevinbarabash commented on lib/rules.js
> +                                          build.div(exponent, index))
What if the index or the exponent aren't numbers?

2017-06-13 01:58 UTC, kevinbarabash commented on lib/rules.js
> +                let index = node.args[1]
You could also do, 
```
if (query.isNthRoot(node)) {
  const [radicand, index] = node.args
  if (query.isPow(radicand)) {
    const [base, exponent] = radicand.args
    if (query.isNumber(exponent) && query.isNumber(index)) {
      ...
    }
  }
}
```

2017-06-13 01:58 UTC, kevinbarabash commented on lib/rules.js
> +        const result = build.apply(
`const result = build.mul(...node.args.map(nthRoot => { ... }))`

2017-06-13 01:58 UTC, kevinbarabash commented on lib/rules.js
> +                let index = node.args[1]
I just published a new version of `math-nodes` that has `isNthRoot`.

2017-06-13 01:58 UTC, kevinbarabash commented on package.json
> +    "eslint": "^4.0.0",
Why this change?

2017-06-13 15:03 UTC, aliang8 commented on package.json
> +    "eslint": "^4.0.0",
Sorry, I did an autoupgrade of all my dependencies. Will fix!

2017-06-15 03:09 UTC, kevinbarabash commented on package.json
> +    "webpack": "^2.6.1"
These dev dependency changes aren't strictly necessary.  Not a huge deal, but please try to avoid updating unless necessary.

2017-06-15 03:09 UTC, k4b7 approved these changes

2017-06-15 03:09 UTC, merged

2017-06-15 03:09 UTC, aliang8 commented on package.json
> +    "webpack": "^2.6.1"
Got it!