Rules Test
semantic-math/math-rules pull request #9
Opened 2017-04-30 19:07 UTC by aliang8

Created `rules.js` and `rules_test.js`.

I'm not sure if that is the way you want to me to export the rules. 

Also, I commented out some of the test cases because of this: 
<img width="626" alt="screen shot 2017-04-30 at 3 05 52 pm" src="https://cloud.githubusercontent.com/assets/16139634/25567201/939845ee-2db6-11e7-8e2e-3b93d10ca4b0.png">

One last note is that the parentheses aren't being parsed/ recognized. Is that true?

2017-04-30 19:36 UTC, kevinbarabash commented
I had a look into the test failures.  It's because math-parser parses `-2` as
```
{ type: 'Number', value: '-2' }
```
whereas `-#a` is parsed as
```
{ type: 'Operation', op: 'neg', args: [ { type: 'Placeholder', name: 'a' } ] }
```

This throws off the `matchNode` because it's trying to match the same structure.  I'm going to change how we parse negative numbers.  I'm tracking that work in https://github.com/semantic-math/math-parser/issues/33.

2017-04-30 19:53 UTC, aliang8 commented
So, math-parser would have to parse `-2` as
`{type: 'Operation', op: 'neg', args: [ { type: Number',  name: '2'}]}`

2017-04-30 20:08 UTC, k4b7 requested changes

2017-04-30 20:08 UTC, k4b7 commented on test/rules_test.js
> +  */
Tests can be temporarily disabled using `it.skip`.  This is preferably to commenting the test out because it only changes one line a diff.

2017-04-30 20:08 UTC, k4b7 commented on test/rules_test.js
> +  });
Please use 4 space tabs.  We should an editor config file and/or eslintrc, but in a separate PR, see https://github.com/semantic-math/math-rules/issues/11.

2017-04-30 20:08 UTC, k4b7 commented on test/rules_test.js
> +  });
Can you have these tests also check variables and expressions, e.g.
```
x / -1 => -x
(x + 1) / -1 => -(x + 1)
```
Also, we should check if rule works when the expression is inside a large expressions, e.g.
```
x^(2 / -1) => x^-2
```

2017-04-30 20:08 UTC, k4b7 commented on lib/rules.js
> +const MULTIPLY_BY_ZERO = defineRuleString('#a * 0', '0');
We should also have `0 * #a => 0`.  Eventually it would be nice to combine both into a single rule, but that should be a separate PR.  See https://github.com/semantic-math/math-rules/issues/10.

2017-04-30 20:08 UTC, k4b7 commented on lib/rules.js
> +const REMOVE_ADDING_ZERO = defineRuleString('#a + 0', '#a');
Add `0 + #a => #a`.

2017-04-30 20:08 UTC, k4b7 commented on lib/rules.js
> +const REMOVE_MULTIPLYING_BY_ONE = defineRuleString('#a * 1', '#a');
Add `1 * #a => #a`

2017-04-30 20:08 UTC, k4b7 commented on test/rules_test.js
> +  });
Each of the tests should test these sorts of variations.

2017-04-30 20:12 UTC, kevinbarabash commented
> So, math-parser would have to parse -2 as
> 
> { type: 'Operation', op: 'neg', args: [ { type: Number', name: '2' } ] }

Yes, that's right.  I've made the change in math-parser published a new version to npm.  You'll have to do `yarn update math-parser` to get the change.

2017-04-30 20:22 UTC, aliang8 commented
I upgraded my math-parser, but the same error is still showing up.

2017-04-30 20:29 UTC, kevinbarabash commented
> I upgraded my math-parser, but the same error is still showing up.

I upgrade math-parser as well and wrote the following test which passes:
```
        it.only('cancel minuses', () => {
            const rule = defineRuleString('-#a / -#b', '#a / #b');
            assert.equal(applyRuleString(rule, '-2 / -1'), '2 / 1');
        });
```

Can you push your changes after upgrading?

2017-04-30 20:33 UTC, aliang8 commented
Yup, will do in a little bit. Sorry for the delay.

2017-04-30 21:33 UTC, kevinbarabash commented
It looks like `yarn update math-parser` didn't actually update package.json like it should've.  My guess is that `yarn update` was run too soon after I published.  Try it again.  It should change the version to `^0.2.2` in the package.json and update yarn.lock as well.

2017-04-30 21:48 UTC, aliang8 commented
I think the command is `yarn upgrade math-parser`. I tried running that command and retesting but it didn't work. I also tried to reclone the `math-parser` repo, but that failed also. I pushed most of the test cases and left the null error one there for you to see.

2017-04-30 21:54 UTC, kevinbarabash commented
I had a quick look at the test cases and they're looking great.  

Yes `yarn upgrade math-parser` is the right command.  Can you paste the output you're seeing?  Here's what I'm seeing:
```
yarn upgrade v0.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
└─ math-parser@0.2.2
✨  Done in 2.30s.
```

2017-04-30 22:00 UTC, aliang8 commented
<img width="318" alt="screen shot 2017-04-30 at 6 00 06 pm" src="https://cloud.githubusercontent.com/assets/16139634/25568355/e4cb9610-2dce-11e7-9977-b08c323a991f.png">

Yup.

2017-04-30 22:03 UTC, kevinbarabash commented
@aliang8 which folder are you running this in?

2017-04-30 22:03 UTC, aliang8 commented
I ran `yarn upgrade math-parser` inside my `math-parser` folder.

2017-04-30 22:05 UTC, kevinbarabash commented
Sorry... I should've been more specific.  You'll need to run `yarn upgrade math-parser` in the `math-rules` folder b/c `math-parser` is a dependency of `math-rules`.

2017-04-30 22:06 UTC, aliang8 commented
I see! All good. I will finish up with the tests.

2017-04-30 22:12 UTC, kevinbarabash commented
> Yup. Also are there any specific changes I should be looking for in math-parser.

The only change I've published recently has been the change to how negative numbers are parsed.  I'm working right now on a change to merge 'Function', 'Operation', and 'Relation' nodes into 'Apply' nodes.  I haven't published that yet, but I don't foresee that affect this diff (fingers crossed).

The only time you'll need to touch your local copy of math-parser is if you need to make changes to the parser.  I'm publishing changes to math-parser as I make them but you don't have publish rights so we can chat about how to test changes across repos locally without publishing when the need arises.

2017-04-30 22:18 UTC, aliang8 commented
> I'm working right now on a change to merge 'Function', 'Operation', and 'Relation' nodes into 'Apply' nodes.

Awesome stuff! Just one last issue with my tests. The ones I had to skip are giving me a weird testing error. Would you mind taking a look at it?

Also, I will try to add a linter based on your preferences to math-rules in a separate PR. Just a heads-up.

2017-04-30 22:27 UTC, kevinbarabash commented
> The ones I had to skip are giving me a weird testing error. Would you mind taking a look at it?

You a test with the same name `remove multiplying by negative one` twice.  Test names must be unique or weird stuff will happen.

2017-04-30 22:32 UTC, aliang8 commented
Good catch! It still didn't fix the error though. 

<img width="476" alt="screen shot 2017-04-30 at 6 32 07 pm" src="https://cloud.githubusercontent.com/assets/16139634/25568560/6a11082e-2dd3-11e7-82a3-107ff73c5ae0.png">

2017-04-30 23:01 UTC, kevinbarabash commented
@aliang8 I had a look at the issue.  The problem is that `populatePattern` wasn't clone the `pattern` template before populating it with nodes from the `placeholders` argument.  Here's the fix:
```
--- a/lib/matcher.js
+++ b/lib/matcher.js
@@ -150,7 +150,7 @@ const checkBounds = (indexes, array) =>
     indexes.start > 0 || indexes.end < array.length - 1
 
 export const populatePattern = (pattern, placeholders) => {
-    return replace(pattern, {
+    return replace(clone(pattern), {
         leave(node) {
             if (node.type === 'Placeholder' && node.name in placeholders) {
                 return clone(placeholders[node.name])
```
Can you make that change as part of you diff?

We'll want to write some tests for these individual functions to that verify that the functions don't modify the arguments, but that can be a separate diff.

2017-04-30 23:30 UTC, kevinbarabash commented
I've updated math-rules to use the versions of math-parser and math-traverse which use `Apply` nodes in place of `Function`, `Operation`, and `Relation` nodes.  Let me know if you run into any issues rebasing.

2017-05-01 01:02 UTC, aliang8 commented
Awesome, that did the trick! I will try to understand why tomorrow.

2017-05-01 02:34 UTC, aliang8 commented
Hey Kevin, I just finished adding the rest of the cases.
Some things that I noticed:

- The SIMPLIFY SIGNS case still returns a `node` error.
- Extra parens or lack thereof 
e.g 
CANCEL_MINUSES
`[ '-(x + 1) / -1' , '( (x + 1) ) / 1' ]` <- extra paren
MULTIPLY_BY_INVERSE
`[ '2 / (3 / 4)' , '2 * 4 / 3' ]` <- loses paren

2017-05-02 02:12 UTC, kevinbarabash commented
I ran the following code:
```
const rule = defineRuleString('-#a / -1', '#a / 1');
const ast = parse('-(x + 1) / -1');
const outAST = applyRule(rule, ast);
console.log(JSON.stringify(outAST, null, 4));
```
and got the following output AST:
```
{
    "type": "Apply",
    "op": "div",
    "args": [
        {
            "type": "Apply",
            "op": "add",
            "args": [
                {
                    "type": "Identifier",
                    "name": "x"
                },
                {
                    "type": "Number",
                    "value": "1"
                }
            ]
        },
        {
            "type": "Number",
            "value": "1"
        }
    ]
}
```
which leads me to believe that the issue is with `print` in `math-parser`, as opposed to the `parse` function.

2017-05-02 02:18 UTC, aliang8 commented
Right, that might in fact be the issue. Does that also explain the case where the solution is missing parentheses?

2017-05-02 02:26 UTC, kevinbarabash commented
I think `[ '2 / (3 / 4)' , '2 * 4 / 3' ]` is fine.  Although there's parens in `2 / (3 / 4)`, the parser doesn't include them in the output because it can describe the order of operations with `Apply:div` nodes only.  Printing out that AST should result in `2 / (3 / 4)`.  The output string is correct b/c the parser parses `2 * 4 / 3` as `2 * (4/3)`.

2017-05-02 02:27 UTC, kevinbarabash commented
I'm going to update `math-parser` with the fix for the extra parens issue.

2017-05-02 02:28 UTC, aliang8 commented
Awesome! It all makes sense now. That was why the parser was structured in that way, order of operations. 👍

2017-05-02 02:30 UTC, kevinbarabash commented
Okay, I've pushed and published the changes to `math-parser`. Sorry about the changes I pushed to `math-rules`.  You'll have to merge again and the update the `math-parser` dependency using `yarn` and then the tests should pass.

2017-05-02 03:25 UTC, k4b7 requested changes
My biggest concern is that the lint check go mixed in here.  If you remove the changes for the lint check and comment out `['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],` and add a TODO this should be good to merge.

2017-05-02 03:25 UTC, kevinbarabash commented on .eslintrc.json
> +}
please keep the lint changes as part of the other PR

2017-05-02 03:25 UTC, kevinbarabash commented on package.json
> +    "lint": "eslint ./ --cache --ignore-pattern .gitignore"
same

2017-05-02 03:25 UTC, kevinbarabash commented on test/rules_test.js
> +            ['x^((x + 1) / 2 * (x + 1) / 2)', 'x^((x + 1) * (x + 1)) / (2 * 2)'],
wow

2017-05-02 03:25 UTC, kevinbarabash commented on test/rules_test.js
> +            ['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],
I'm a little concerned by this one... I would've expected the output to be `x^((x + 1) / (2 * 2))`

2017-05-02 03:25 UTC, kevinbarabash commented on test/rules_test.js
> +            ['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],
probably something wrong with the `print` function in `math-parser`... can you verify what the output AST is for this and open a `math-parser` issue if necessary?

2017-05-02 03:32 UTC, aliang8 commented on test/rules_test.js
> +            ['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],
Should I include this in the TODO?

2017-05-02 03:39 UTC, kevinbarabash commented on test/rules_test.js
> +// add more test cases (if possible)
in the future put the TODO closer to where the issue is

2017-05-02 03:40 UTC, k4b7 approved these changes

2017-05-02 03:40 UTC, aliang8 commented on test/rules_test.js
> +// add more test cases (if possible)
Will keep that in mind!

2017-05-02 03:42 UTC, aliang8 commented on test/rules_test.js
> +            ['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],
I printed out the ast for the test case:

`{
    "type": "Apply",
    "op": "pow",
    "args": [
        {
            "type": "Identifier",
            "name": "x",
            "loc": {
                "start": 0,
                "end": 1
            }
        },
        {
            "type": "Apply",
            "op": "div",
            "args": [
                {
                    "type": "Apply",
                    "op": "add",
                    "args": [
                        {
                            "type": "Identifier",
                            "name": "x",
                            "loc": {
                                "start": 4,
                                "end": 5
                            }
                        },
                        {
                            "type": "Number",
                            "value": "1",
                            "loc": {
                                "start": 8,
                                "end": 9
                            }
                        }
                    ],
                    "loc": {
                        "start": 4,
                        "end": 9
                    }
                },
                {
                    "type": "Apply",
                    "op": "mul",
                    "args": [
                        {
                            "type": "Number",
                            "value": "2",
                            "loc": {
                                "start": 13,
                                "end": 14
                            }
                        },
                        {
                            "type": "Number",
                            "value": "2",
                            "loc": {
                                "start": 17,
                                "end": 18
                            }
                        }
                    ],
                    "loc": {
                        "start": 6,
                        "end": 13
                    }
                }
            ],
            "loc": {
                "start": 0,
                "end": 13
            }
        }
    ],
    "loc": {
        "start": 0,
        "end": 18
    }
}`

2017-05-02 03:42 UTC, merged

2017-05-02 03:43 UTC, aliang8 commented on test/rules_test.js
> +            ['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],
`
{
    "type": "Apply",
    "op": "pow",
    "args": [
        {
            "type": "Identifier",
            "name": "x",
            "loc": {
                "start": 0,
                "end": 1
            }
        },
        {
            "type": "Apply",
            "op": "div",
            "args": [
                {
                    "type": "Apply",
                    "op": "add",
                    "args": [
                        {
                            "type": "Identifier",
                            "name": "x",
                            "loc": {
                                "start": 4,
                                "end": 5
                            }
                        },
                        {
                            "type": "Number",
                            "value": "1",
                            "loc": {
                                "start": 8,
                                "end": 9
                            }
                        }
                    ],
                    "loc": {
                        "start": 4,
                        "end": 9
                    }
                },
                {
                    "type": "Apply",
                    "op": "mul",
                    "args": [
                        {
                            "type": "Number",
                            "value": "2",
                            "loc": {
                                "start": 13,
                                "end": 14
                            }
                        },
                        {
                            "type": "Number",
                            "value": "2",
                            "loc": {
                                "start": 17,
                                "end": 18
                            }
                        }
                    ],
                    "loc": {
                        "start": 6,
                        "end": 13
                    }
                }
            ],
            "loc": {
                "start": 0,
                "end": 13
            }
        }
    ],
    "loc": {
        "start": 0,
        "end": 18
    }
}
`

2017-05-02 03:43 UTC, aliang8 commented on test/rules_test.js
> +            ['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],
`{  
   "type":"Apply",
   "op":"pow",
   "args":[  
      {  
         "type":"Identifier",
         "name":"x",
         "loc":{  
            "start":0,
            "end":1
         }
      },
      {  
         "type":"Apply",
         "op":"div",
         "args":[  
            {  
               "type":"Apply",
               "op":"add",
               "args":[  
                  {  
                     "type":"Identifier",
                     "name":"x",
                     "loc":{  
                        "start":4,
                        "end":5
                     }
                  },
                  {  
                     "type":"Number",
                     "value":"1",
                     "loc":{  
                        "start":8,
                        "end":9
                     }
                  }
               ],
               "loc":{  
                  "start":4,
                  "end":9
               }
            },
            {  
               "type":"Apply",
               "op":"mul",
               "args":[  
                  {  
                     "type":"Number",
                     "value":"2",
                     "loc":{  
                        "start":13,
                        "end":14
                     }
                  },
                  {  
                     "type":"Number",
                     "value":"2",
                     "loc":{  
                        "start":17,
                        "end":18
                     }
                  }
               ],
               "loc":{  
                  "start":6,
                  "end":13
               }
            }
         ],
         "loc":{  
            "start":0,
            "end":13
         }
      }
   ],
   "loc":{  
      "start":0,
      "end":18
   }
}
`

2017-05-02 03:44 UTC, kevinbarabash commented
Yay! 🎉  That was a bit of a slog but it uncovered a number of issues which got fixed. 👍

2017-05-02 03:44 UTC, aliang8 commented on test/rules_test.js
> +            ['x^((x + 1) / 2 / 2)', 'x^(x + 1) / (2 * 2)'],
Here is the AST for that test case: 
<img width="343" alt="screen shot 2017-05-01 at 11 44 27 pm" src="https://cloud.githubusercontent.com/assets/16139634/25603268/2e5560e6-2ec8-11e7-90cf-52d7ce8e3076.png">